### ISSUE TITLE
Exception raised on waiting for all jobs to finish

### ISSUE THREAD

**Issue by roybh1** [lewagon/wait-on-check-action#28]
Hi,
We are using this plugin to wait on all checks on pull request to allow dynamic CI jobs with BORS (merge queuing)
The step sometimes fail on:
`/usr/bin/docker run --name e4f55beca1679d4d5e9e170cc080dc764b_ec7072 --label 5588e4 --workdir /github/workspace --rm -e INPUT_REF -e INPUT_REPO-TOKEN -e INPUT_WAIT-INTERVAL -e INPUT_RUNNING-WORKFLOW-NAME -e INPUT_CHECK-NAME -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/epsagon-backend/epsagon-backend":"/github/workspace" 5588e4:f55beca1679d4d5e9e170cc080dc764b  "" "" "***" "5" "jobs-ended"
/entrypoint.rb:23:in `query_check_status': undefined method `reject' for nil:NilClass (NoMethodError)
	from /entrypoint.rb:34:in `<main>'`

The step is defined as:
`jobs:
  jobs-ended:
    runs-on: ubuntu-20.04
    steps:
      - name: Wait on tests
        uses: lewagon/wait-on-check-action@v0.2
        with:
          ref: ${{ github.event.after }} # can be commit SHA or tag too
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 20
          running-workflow-name: "jobs-ended"`

**Comment by progapandist** [comment]
Hi! Please try using `lewagon/wait-on-check-action@master`, a lot of things has been fixed since the release and it's hight time I bump a version (still can't get to it though). Tell me if it solved your problem :)

**Comment by matiasalbarello** [comment]
Hi @roybh1. Could you confirm that this issue persists using the last version (v1.1.0)? Thanks!
