### ISSUE TITLE
Repo key is required from v1.0.0

### ISSUE THREAD

**Issue by sshane** [lewagon/wait-on-check-action#66]
When updating from v0.2 to v1.0.0, I noticed that the repo key is a requirement now, is there any reason for this? Accessing the runs for a repo seems to be public still.

The error I get when I don't specify `repo-token`: https://github.com/commaai/openpilot/runs/6807857911?check_suite_focus=true

```
/usr/local/bundle/gems/octokit-4.20.0/lib/octokit/response/raise_error.rb:14:in `on_complete': GET https://api.github.com/repos/commaai/openpilot/commits/master/check-runs: 401 - Bad credentials // See: https://docs.github.com/rest (Octokit::Unauthorized)
	from /usr/local/bundle/gems/faraday-1.3.0/lib/faraday/middleware.rb:19:in `block in call'
	from /usr/local/bundle/gems/faraday-1.3.0/lib/faraday/response.rb:59:in `on_complete'
	from /usr/local/bundle/gems/faraday-1.3.0/lib/faraday/middleware.rb:18:in `call'
	from /usr/local/bundle/gems/octokit-4.[20](https://github.com/commaai/openpilot/runs/6807857911?check_suite_focus=true#step:3:21).0/lib/octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
	from /usr/local/bundle/gems/octokit-4.20.0/lib/octokit/middleware/follow_redirects.rb:61:in `call'
	from /usr/local/bundle/gems/faraday-1.3.0/lib/faraday/request/retry.rb:148:in `call'
	from /usr/local/bundle/gems/faraday-1.3.0/lib/faraday/rack_builder.rb:154:in `build_response'
	from /usr/local/bundle/gems/faraday-1.3.0/lib/faraday/connection.rb:492:in `run_request'
	from /usr/local/bundle/gems/faraday-1.3.0/lib/faraday/connection.rb:198:in `get'
	from /usr/local/bundle/gems/sawyer-0.8.2/lib/sawyer/agent.rb:94:in `call'
	from /usr/local/bundle/gems/octokit-4.20.0/lib/octokit/connection.rb:156:in `request'
	from /usr/local/bundle/gems/octokit-4.20.0/lib/octokit/connection.rb:19:in `get'
	from /usr/local/bundle/gems/octokit-4.20.0/lib/octokit/client/checks.rb:68:in `check_runs_for_ref'
	from /app/services/github_checks_verifier.rb:[29](https://github.com/commaai/openpilot/runs/6807857911?check_suite_focus=true#step:3:30):in `query_check_status'
	from /app/services/github_checks_verifier.rb:92:in `wait_for_checks'
	from /app/services/github_checks_verifier.rb:20:in `call'
	from /app/services/application_service.rb:5:in `call'
	from /entrypoint.rb:19:in `<main>'
```

**Comment by matiasalbarello** [comment]
Fixed on v1.1.2
